name: Test Indico fetcher

on:
  - push
  - workflow_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List directory
        run: |
          find

      - name: Run fetcher
        run: |
          ./indico-fetcher.py

      - name: List directory
        run: |
          find
